---
- name: Prepare
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Copy service account content into a file 
      become: true
      copy:
        content: "{{ gcp_service_account }}"
        dest: /tmp/credentials.json
