---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    hive_port: 10000
  tasks:
    - name: Wait for Hive server
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ hive_port }}"
        timeout: 300
      when: is_master == 1

    - name: Wait for Monitor server
      wait_for:
        host: "{{ ansible_host }}"
        port: 9999
        timeout: 300
      when: is_master == 1

    - name: Wait for Dev console
      wait_for:
        host: "{{ ansible_host }}"
        port: 8082
        timeout: 300
      when: is_master == 1

    - name: Check if all nodes are up
      uri:
        url: "http://{{ ansible_host }}:9999/api/get/nodes"
        follow_redirects: none
        method: GET
      register: _result
      until:
        - _result.status == 200
        - _result.json.nodesDown |length == 0
        - _result.json.nodesUp | length == nodes
      retries: 5 # 12 * 5 seconds = 1min
      delay: 5 # Every 5 seconds

