language: python
python: "3.7"
os: linux
dist: bionic
services:
  - docker
env:
  - distribution: "centos"
    version: "7"
  - distribution: "ubuntu"
    version: 'bionic'
before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version}
    --tag=${distribution}-${version}:ansible travis'
install:
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg
script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-indexima-install:ro
    ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook
    -v /etc/ansible/roles/ansible-indexima-install/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook
    -v /etc/ansible/roles/ansible-indexima-install/tests/test.yml -i /etc/ansible/roles/ansible-indexima-install/examples/hosts.local'
  # Idempotence check on 'conf' tag
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook
  -v /etc/ansible/roles/ansible-indexima-install/tests/test.yml -i /etc/ansible/roles/ansible-indexima-install/examples/hosts.local -t "conf"
  | grep -q "changed=0.*failed=0"
  && (echo "Idempotence test: pass" && exit 0)
  || (echo "Idempotence test: fail" && exit 1)'
  # Idempotence check on 'istart' tag
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook
  -v /etc/ansible/roles/ansible-indexima-install/tests/test.yml -i /etc/ansible/roles/ansible-indexima-install/examples/hosts.local -t "istart" 
  | grep -q "changed=0.*failed=0"
    && (echo "Idempotence test: pass" && exit 0)
    || (echo "Idempotence test: fail" && exit 1)'
  # Idempotence check 'istop' tag
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook
  -v /etc/ansible/roles/ansible-indexima-install/tests/test.yml -i /etc/ansible/roles/ansible-indexima-install/examples/hosts.local -t "istop"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook
  -v /etc/ansible/roles/ansible-indexima-install/tests/test.yml -i /etc/ansible/roles/ansible-indexima-install/examples/hosts.local -t "istop" 
  | grep -q "changed=0.*failed=0"
    && (echo "Idempotence test: pass" && exit 0)
    || (echo "Idempotence test: fail" && exit 1)'
  # Cleanup
  - 'sudo docker rm -f "$(cat ${container_id})"'
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
  slack:
    secure: UKmi5zLnAW3y5yyiDdBt3HtYGoB2G9sMv72vTnwiANeBDuktwfAiA5FoI2MKTzCmkBh/ZvSJtQxo6zCdsxZ66Vzz+rWfaG/oGdG/3l4KGHln5NFpggHZ3DS1OlkDpP9oMbVRXQ0m0l/cgGiMRbxil2oW3uFEXCttmm9BuwUhc9Tn43ftqh4+fV9XO5o6gDMk4FcQLwpFoU5dMwWGZjVWNelYNNj0lxfbaKHxp+MvjhpJ2iE5Fd55XO6TSA8hVXHClfOlO/8hQEQmR4Mtnxb0rm36NIzdeiDCHXytBhn0ETpXEAOGX1jZxT/udzutSMlRheTXaMe0U3F5DlkxligmtOiW0i+NOx6RgT3upxAITxT5W7xXsO3CCtGmN5SOocqGOPbWRMil52WGgt2HfR7bvBe3t+z4EB4NdKt5tSYHWEoKJ90/Olj2tTCrUWRIatvxBznDrWH7Y6S5cuigtGcoiRYVTrzQBMcMohcJCEevAk3q1RtQtJ2Nxxy0FqMQ5lDlYCOmIM9O3XmeYCCqYCtGgNVgYrBO56mqRQyHnOFfJicbxnSQNoZlt5Heouf0BzC3zXNQ9E+DSBCUD3PW3ztF7u0761Il2lF1uiV8yeVvdNJWm/CzQN4XbcY8XtAbRY4cuolUt900yLFae4yh/lua8jMIzhAPv4+ayOJQ5FR6T48=
