language: python
python: "3.7"
services:
  - docker
env:
  - MOL_TEST: "local"
  - MOL_TEST: "docker-auth"
  - MOL_TEST: "docker"
    ANSIBLE_VERSION: "2.8.1"
  - MOL_TEST: "docker"
    ANSIBLE_VERSION: "4.0.0"
    INDEXIMA_VERSION: "2021.2.1390.2"
  - MOL_TEST: "docker"
    MOL_DISTRO: "centos7"
  - MOL_TEST: "docker"
    MOL_DISTRO: "ubuntu1604"
  - MOL_TEST: "amazon"
    MOL_AMI_NAME: "amzn2-ami-hvm-2.0*"
    MOL_AMI_OWNER: "amazon"
    MOL_SSH_USER: "ec2-user"
    MOL_ENV_NAME: "amazon"
jobs:
  exclude:
    - if: branch != master AND branch !~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      env:
        - MOL_TEST: "docker-auth"
        - MOL_TEST: "docker"
          ANSIBLE_VERSION: "2.8.1"
        - MOL_TEST: "docker"
          MOL_DISTRO: "centos7"
        - MOL_TEST: "docker"
          MOL_DISTRO: "ubuntu1604"
        - MOL_TEST: "amazon"
          MOL_AMI_NAME: "amzn2-ami-hvm-2.0*"
          MOL_AMI_OWNER: "amazon"
          MOL_SSH_USER: "ec2-user"
          MOL_ENV_NAME: "amazon"
install:
  - pip install ansible==${ANSIBLE_VERSION:-2.10.1} molecule==3.0.8 molecule-ec2==0.2 molecule-docker==0.2.4 boto3 yamllint ansible-lint docker
script:
  - ./travis/script_molecule.sh
notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/?branch=master
  slack:
    secure: UKmi5zLnAW3y5yyiDdBt3HtYGoB2G9sMv72vTnwiANeBDuktwfAiA5FoI2MKTzCmkBh/ZvSJtQxo6zCdsxZ66Vzz+rWfaG/oGdG/3l4KGHln5NFpggHZ3DS1OlkDpP9oMbVRXQ0m0l/cgGiMRbxil2oW3uFEXCttmm9BuwUhc9Tn43ftqh4+fV9XO5o6gDMk4FcQLwpFoU5dMwWGZjVWNelYNNj0lxfbaKHxp+MvjhpJ2iE5Fd55XO6TSA8hVXHClfOlO/8hQEQmR4Mtnxb0rm36NIzdeiDCHXytBhn0ETpXEAOGX1jZxT/udzutSMlRheTXaMe0U3F5DlkxligmtOiW0i+NOx6RgT3upxAITxT5W7xXsO3CCtGmN5SOocqGOPbWRMil52WGgt2HfR7bvBe3t+z4EB4NdKt5tSYHWEoKJ90/Olj2tTCrUWRIatvxBznDrWH7Y6S5cuigtGcoiRYVTrzQBMcMohcJCEevAk3q1RtQtJ2Nxxy0FqMQ5lDlYCOmIM9O3XmeYCCqYCtGgNVgYrBO56mqRQyHnOFfJicbxnSQNoZlt5Heouf0BzC3zXNQ9E+DSBCUD3PW3ztF7u0761Il2lF1uiV8yeVvdNJWm/CzQN4XbcY8XtAbRY4cuolUt900yLFae4yh/lua8jMIzhAPv4+ayOJQ5FR6T48=
