---
# collect stats about the dir
- name: clean_galactica.yaml / Check galactica/lib exists
  stat:
    path: '{{ galactica_path }}/lib'
  register: dir_to_delete

# delete directory if condition is true
- name: clean_galactica.yaml / Purge {{ galactica_path }}/lib
  file:
    state: absent
    path: '{{ galactica_path }}/lib'
  when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir

# Find all jar in  dir
- name: clean_galactica.yaml / Find all jar in {{ galactica_path }} dir
  find:
    paths: '{{ galactica_path }}'
    patterns: "*.jar"
  register: files_to_delete

# Remove all files found above
- name: clean_galactica.yaml / Remove all jar in {{ galactica_path }} dir
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
