---
# collect stats about the dir
- name: Check {{ dc_path }}/lib exists
  stat:
    path: '{{ dc_path }}/lib'
  register: dir_to_delete

# delete directory if condition is true
- name: Purge {{ dc_path }}/lib
  file:
    state: absent
    path: '{{ dc_path }}/lib'
  when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir

# Find all jar in  dir
- name: Find all jar in {{ dc_path }} dir
  find:
    paths: '{{ dc_path }}'
    patterns: "*.jar"
  register: files_to_delete

# Remove all files found above
- name: Remove all jar in {{ dc_path }} dir
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
