---
- name: Copy galactica.conf copy to servers
  copy:
    src: conf/galactica.conf
    dest: "{{ indexima_path }}/galactica/conf/galactica.conf"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  ignore_errors: yes

- name: Copy galactica-env.sh copy to servers
  copy:
    src: conf/galactica-env.sh
    dest: "{{ indexima_path }}/galactica/conf/galactica-env.sh"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0755'
  ignore_errors: yes

- name: Copy monitor-site.xml copy to servers
  copy:
    src: conf/monitor-site.xml
    dest: "{{ indexima_path }}/galactica/conf/monitor-site.xml"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  ignore_errors: yes

- name: Copy hive-site.xml copy to servers
  copy:
    src: conf/hive-site.xml
    dest: "{{ indexima_path }}/galactica/conf/hive-site.xml"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  ignore_errors: yes

- name: Copy log4j2.xml copy to servers
  copy:
    src: conf/log4j2.xml
    dest: "{{ indexima_path }}/galactica/conf/log4j2.xml"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  ignore_errors: yes

- name: Copy log4j.xml copy to servers
  copy:
    src: conf/log4j.xml
    dest: "{{ indexima_path }}/galactica/conf/log4j.xml"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  ignore_errors: yes

- name: Copy optimize_index.json copy to servers
  copy:
    src: conf/optimize_index.json
    dest: "{{ galactica_path }}/conf/optimize_index.json"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  ignore_errors: yes

- name: Copy notifications.json copy to servers
  copy:
    src: conf/notifications.json
    dest: "{{ galactica_path }}/conf/notifications.json"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  ignore_errors: yes

- name: Copy supported_dbs.json copy to servers
  copy:
    src: conf/supported_dbs.json
    dest: "{{ galactica_path }}/conf/supported_dbs.json"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  ignore_errors: yes