---
- name: Copy galactica.conf template to servers
  template:
    src: galactica.conf
    dest: "{{ indexima_path }}/galactica/conf/galactica.conf"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'

- name: Copy galactica-env.sh template to servers
  template:
    src: galactica-env.sh
    dest: "{{ indexima_path }}/galactica/conf/galactica-env.sh"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0755'

- name: Copy monitor-site.xml template to servers
  template:
    src: monitor-site.xml
    dest: "{{ indexima_path }}/galactica/conf/monitor-site.xml"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'

- name: Copy hive-site.xml template to servers
  template:
    src: hive-site.xml
    dest: "{{ indexima_path }}/galactica/conf/hive-site.xml"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'

- name: Copy log4j2.xml template to servers
  template:
    src: log4j2.xml
    dest: "{{ indexima_path }}/galactica/conf/log4j2.xml"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'

- name: Copy optimize_index.json template to servers
  template:
    src: optimize_index.json
    dest: "{{ galactica_path }}/conf/optimize_index.json"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'

- name: Copy notifications.json template to servers
  template:
    src: notifications.json
    dest: "{{ galactica_path }}/conf/notifications.json"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'

- name: Copy supported_dbs.json template to servers
  template:
    src: supported_dbs.json
    dest: "{{ galactica_path }}/conf/supported_dbs.json"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'

- name: Copy jaas.conf template to servers
  template:
    src: jaas.conf
    dest: "{{ galactica_path }}/jaas.conf"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  when: kerberos_principal is defined and kerberos_keytab is defined

- name: Copy google_credentials.json file to servers
  copy:
    src: "credentials.json"
    dest: "{{ google_credentials }}"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  when: google_credentials is defined
  tags: test-google