---
- name: Copy config_vd2.sh template to devconsole master
  template:
    src: config_vd2.sh
    dest: "{{ dc_path }}/config.sh"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  when: is_master == 1

- name: Copy log4j2_vd2.xml template to master
  template:
    src: log4j2_vd2.xml
    dest: "{{ dc_path }}/log4j2.xml"
    owner: "{{ service_user |d('root') }}"
    group: "{{ service_user |d('root') }}"
    mode: '0644'
  when: is_master == 1
