---
- name: Copy Galactica Master service file to all nodes
  become: yes
  become_user: root
  template:
    src: indeximam.service
    dest: /etc/systemd/system/indeximam.service
    owner: "root"
    group: "root"
    mode: '0644'
  when:
    - is_master == 1
    - ha == 0

- name: Copy Galactica Worker service file to all nodes
  become: yes
  become_user: root
  template:
    src: indeximas.service
    dest: /etc/systemd/system/indeximas.service
    owner: "root"
    group: "root"
    mode: '0644'
  when:
    - is_master == 0
    - ha == 0

- name: Copy Visualdoop service file to master node
  become: yes
  become_user: root
  template:
    src: visualdoop.service
    dest: /etc/systemd/system/visualdoop.service
    owner: "root"
    group: "root"
    mode: '0644'
  when:
    - is_master == 1
    - not devconsole|bool

- name: Copy Dev Console service file to master node
  become: yes
  become_user: root
  template:
    src: devconsole.service
    dest: /etc/systemd/system/devconsole.service
    owner: "root"
    group: "root"
    mode: '0644'
  when:
    - is_master == 1
    - devconsole|bool

- name: Copy Galactica ha service file to all nodes
  become: yes
  become_user: root
  template:
    src: indexima.service
    dest: /etc/systemd/system/indexima.service
    owner: "root"
    group: "root"
    mode: '0644'
  when: ha == 1