---
- name: deploy_service.yaml / Copy Visualdoop service file to master node
  become: yes
  become_user: root
  template:
    src: visualdoop.service
    dest: /etc/systemd/system/visualdoop.service
    owner: "root"
    group: "root"
    mode: '0644'
  when:
    - is_master == 1

- name: deploy_service.yaml / Copy Galactica service file to all nodes
  become: yes
  become_user: root
  template:
    src: indexima.service
    dest: /etc/systemd/system/indexima.service
    owner: "root"
    group: "root"
    mode: '0644'