---
## ORACLE
- name: Copy oracle jdbc driver in /driver
  copy:
    src: ojdbc8.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when:
    - oracle
    - internet == 0

- name: Download oracle jdbc driver in /driver
  get_url:
    url: "https://download.oracle.com/otn-pub/otn_software/jdbc/198/ojdbc8.jar"
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when:
    - oracle
    - internet == 1

## DB2
- name: Copy db2 jdbc driver in /driver
  copy:
    src: db2jcc4.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when: db2

## SNOWFLAKE
- name: Copy snowflake jdbc driver in /driver
  copy:
    src: snowflake-jdbc-3.9.2.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when:
    - snowflake
    - internet == 0

- name: Download snowflake jdbc driver in /driver
  get_url:
    url: "https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.9.2/snowflake-jdbc-3.9.2.jar"
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when:
    - snowflake
    - internet == 1

## HIVE
- name: Copy hive jdbc driver in /driver
  copy:
    src: hive-jdbc-1.2.1.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when: hive

## POSTGRES
- name: Copy postgres jdbc driver in /driver
  copy:
    src: postgresql-42.2.2.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when:
    - postgres
    - internet == 0

- name: Download postgres jdbc driver in /driver
  get_url:
    url: "https://jdbc.postgresql.org/download/postgresql-42.2.18.jar"
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when:
    - postgres
    - internet == 1

## SQLSERVER
- name: Copy sqlserver jdbc driver in /driver
  copy:
    src: sqljdbc42.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when: sqlserver

## MYSQL
- name: Copy mysql jdbc driver in /driver
  copy:
    src: mysql-connector-java-8.0.18.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when: mysql

## BIGQUERY
- name: Copy bigquery jdbc driver in /driver
  copy:
    src: googlebigquery.jdbc42-1.2.2.1004.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when: bigquery

## REDSHIFT
- name: Copy redshift jdbc driver in /driver
  copy:
    src: redshift-jdbc42-1.2.37.1061.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when:
    - redshift
    - internet == 0

- name: Download redshift jdbc driver in /driver
  get_url:
    url: "https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.37.1061/RedshiftJDBC42-1.2.37.1061.jar"
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when:
    - redshift
    - internet == 1

## IMPALA
- name: Copy Impala jdbc driver in /driver
  copy:
    src: jdbc-2.5.5.1007.jar
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  when: impala