---
## Local drivers
- name: Copy jdbc drivers in /driver
  copy:
    src: "{{ item }}"
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  with_fileglob:
    - files/drivers/*
  when:
    - drivers |bool
    - drivers_url is not defined

- name: List all files present in {{ drivers_url }}
  uri:
    url: "{{ drivers_url }}"
    return_content: yes
  register: driver_files
  when:
    - drivers |bool
    - drivers_url is defined and drivers_url != ""

- name: Download all jar files present in {{ drivers_url }}
  get_url:
    url: "{{ drivers_url }}/{{ item }}"
    dest: "{{ galactica_path }}/driver"
  with_items: >
    {{ driver_files | regex_findall("[a-zA-Z0-9\.\-\_]+\.jar") }}