---
## Local drivers
- name: Copy jdbc drivers in /driver
  copy:
    src: "{{ item }}"
    dest: "{{ galactica_path }}/driver"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  with_fileglob:
    - files/drivers/*
  when:
    - drivers |bool
    - drivers_url is not defined
