---
- name: install_visualdoop.yaml / Copy VD2 zip archive (No internet mode)
  copy:
    src: "{{ vd2_file }}"
    dest: "{{ vd2_archive }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0644'
  when: internet == 0
  register: copy_result

- name: install_visualdoop.yaml / Download VD2 zip archive
  get_url:
    url: "{{ vd2_url }}"
    dest: "{{ vd2_archive }}"
  when:
    - internet == 1
    - internal_use == 0
  register: download_result

- name: install_visualdoop.yaml / Download VD2 zip archive from internal repository (internal use only)
  get_url:
    url: "{{ internal_url }}/indexima-installer-visual2/{{ indexima_version }}/indexima-installer-visual2-{{ indexima_version }}.zip"
    dest: "{{ vd2_archive }}"
    url_username: "{{ internal_username }}"
    url_password: "{{ internal_password }}"
  when:
    - internet == 1
    - internal_use == 1
  register: download_result

- name: install_visualdoop.yaml / Check if something changed in VD2
  check_mode: true
  unarchive:
    remote_src: yes
    src: "{{ vd2_archive }}"
    dest: "{{ indexima_path }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
  register: check_vd2
  tags: ['check']

- import_tasks: clean_vd2.yaml
  tags: ['clean']
  when: check_vd2.changed

- name: install_visualdoop.yaml / Extract VD2 release
  unarchive:
    remote_src: yes
    src: "{{ vd2_archive }}"
    dest: "{{ indexima_path }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"

- name: install_visualdoop.yaml / Copy keystore file if SSL is enabled
  copy:
    src: "{{ keystore_file }}"
    dest: "{{ vd2_path }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0644'
  when: ssl == 1
