---
- name: Copy Dev Console zip archive (No internet mode)
  copy:
    src: "{{ dc_file }}"
    dest: "{{ dc_archive }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0644'
  when: internet == 0
  register: copy_result

- name: Download Dev Console zip archive
  get_url:
    url: "{{ dc_url }}"
    dest: "{{ dc_archive }}"
  when:
    - internet == 1
    - internal_use == 0
  register: download_result

- name: Download Dev Console zip archive from internal repository (internal use only)
  get_url:
    url: "{{ internal_url }}/indexima-installer-devconsole/{{ indexima_version }}/indexima-installer-devconsole-{{ indexima_version }}.zip"
    dest: "{{ dc_archive }}"
    url_username: "{{ internal_username }}"
    url_password: "{{ internal_password }}"
  when:
    - internet == 1
    - internal_use == 1
  register: download_result

- name: Check if something changed in Dev console
  check_mode: true
  unarchive:
    remote_src: yes
    src: "{{ dc_archive }}"
    dest: "{{ indexima_path }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
  register: check_dc
  tags: ['check']

- import_tasks: clean_dc.yaml
  tags: ['clean']
  when: check_dc.changed

- name: Extract Dev console release
  unarchive:
    remote_src: yes
    src: "{{ dc_archive }}"
    dest: "{{ indexima_path }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"

- name: Copy keystore file if SSL is enabled
  copy:
    src: "{{ keystore_file }}"
    dest: "{{ dc_path }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0644'
  when: ssl == 1
