---
- name: install_prep.yaml / Create Install Path Dir
  become: yes
  become_user: root
  file:
    path: "{{ install_path }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0755'
  register: install

- name: install_prep.yaml / Create Log Dir
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0755'
  with_items: "{{ indexima_logs }}"

- name: install_prep.yaml / Create extract dir
  become: yes
  become_user: root
  file:
    path: "{{ indexima_path }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0755'
  register: dir

- name: install_prep.yaml / Create folder TEZ
  become: yes
  become_user: root
  file:
    path: "{{ galactica_path }}/tez"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0755'
  register: dir
  when:
    - drivers == "1"
    - hadoop_version_major == "3"