---
- name: license.yaml / Copy license to galactica/conf
  copy:
    src: indexima.lic
    dest: "{{ galactica_path }}/conf"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0644'