---
# tasks file for ansible-indexima-install
- import_tasks: set_facts.yaml
  tags: [ 'always' ]

- import_tasks: uninstall.yaml
  tags: [ 'never', 'uninstall' ]

### Install
## Install Prep
- import_tasks: install_prep.yaml
  tags: ['install', 'prerequisites', 'ginstall', 'vinstall', 'prep' ]

- import_tasks: prerequisites.yaml
  tags: [ 'install', 'prerequisites']
  become: yes
  become_user: root

## Galactica

- import_tasks: install_galactica.yaml
  tags: [ 'install', 'update', 'ginstall', 'gupdate']

## Visualdoop2

- import_tasks: install_visualdoop.yaml
  tags: ['install', 'update', 'vinstall', 'vupdate']
  when:
    - is_master == 1

- import_tasks: deploy_service.yaml
  tags: [ 'service', 'install', 'update' ]
  when: systemd| bool

- import_tasks: config_galactica.yaml
  tags: [ 'conf', 'gconf' ]

- import_tasks: config_custom.yaml
  tags: [ 'never', 'conf-custom' ]

- import_tasks: config_visualdoop.yaml
  tags: [ 'conf', 'vconf' ]
  when:
    - is_master == 1

- import_tasks: drivers.yaml
  tags: [ 'driver', 'update', 'gupdate', 'install', 'ginstall' ]

- import_tasks: azure_datalake.yaml
  become: yes
  become_user: root
  tags: [ 'never', 'azure_datalake' ]

- import_tasks: stop_indexima.yaml
  tags: [ 'never', 'restart', 'stop' ]
  when: not systemd| bool

- import_tasks: start_indexima.yaml
  tags: [ 'restart', 'start' ]
  when: not systemd| bool

- import_tasks: manage_service.yaml
  tags: [ 'irestart', 'restart' ]
  when: systemd| bool

- import_tasks: jdbc_url.yaml
  tags: [ 'always', 'jdbc']

- import_tasks: wait_for_service.yml
  tags: [ 'wait' ]
