---
# tasks file for ansible-indexima-install
- import_tasks: set_facts.yaml
  tags: [ 'always' ]

- import_tasks: uninstall.yaml
  tags: [ 'never', 'uninstall' ]

### Install
## Install Prep
- import_tasks: install_prep.yaml
  tags: ['install', 'prerequisites', 'install-galactica', 'install-visualdoop' ]

- import_tasks: prerequisites.yaml
  tags: [ 'install', 'prerequisites' ]
  become: yes
  become_user: root
  when: yarn_deploy == 0

## Galactica

- import_tasks: install_galactica.yaml
  tags: [ 'install', 'update', 'install-galactica', 'update-galactica']
  when: yarn_deploy == 0

- import_tasks: install_galactica.yaml
  tags: [ 'install', 'update', 'install-galactica', 'update-galactica']
  when:
    - yarn_deploy == 1
    - is_edge == 1

## Visualdoop2

- import_tasks: install_visualdoop.yaml
  tags: ['install', 'update', 'install-visualdoop', 'update-visualdoop']
  when: is_master == 1 or is_edge == 1

- import_tasks: deploy_service.yaml
  tags: [ 'service', install', 'update' ]

- import_tasks: config_galactica.yaml
  tags: [ 'conf', 'conf-galactica' ]

- import_tasks: config_custom.yaml
  tags: [ 'never', 'conf-custom' ]

- import_tasks: config_visualdoop.yaml
  tags: [ 'conf', 'conf-visualdoop' ]
  when: is_master == 1 or is_edge == 1

- import_tasks: drivers.yaml
  tags: [ 'never', 'driver', 'update', 'update-galactica', 'install', 'install-galactica' ]

- import_tasks: hadoop.yaml
  become: yes
  become_user: root
  tags: [ 'never', 'hadoop' ]

- import_tasks: license.yaml
  tags: [ 'never', 'license' ]

- import_tasks: stop_indexima.yaml
  tags: [ 'never', 'restart', 'stop' ]
  when: yarn_deploy == 0

- import_tasks: start_indexima.yaml
  tags: [ 'never', 'restart', 'start' ]
  when: yarn_deploy == 0

- import_tasks: manage_service.yaml
  tags: [ 'irestart' ]

- import_tasks: jdbc_url.yaml
  tags: [ 'always', 'jdbc']
  when: yarn_deploy == 0

- import_tasks: wait_for_service.yml
  tags: [ 'wait' ]
  when: yarn_deploy == 0