---
- import_tasks: set_facts.yaml
  tags: [ 'always' ]

- import_tasks: uninstall.yaml
  tags: [ 'never', 'reinstall', 'uninstall' ]

### Install
## Install Prep
- import_tasks: install_prep.yaml
  tags: ['install', 'update', 'install-galactica', 'update-galactica', 'install-visualdoop', 'update-visualdoop']

# tasks file for indexima-prerequisites
- import_tasks: set_facts.yaml
  tags: [ 'always' ]

- import_tasks: centos.yaml
  when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "Amazon"
  tags: ['centos']

- import_tasks: debian.yaml
  when: ansible_facts['distribution']  == "Debian" or ansible_facts['distribution'] == "Ubuntu"
  tags: ['debian']

## Galactica

- import_tasks: install_galactica.yaml
  tags: [ 'install', 'update', 'install-galactica', 'update-galactica']

## Visualdoop2

- import_tasks: install_visualdoop.yaml
  tags: ['install', 'update', 'install-visualdoop', 'update-visualdoop']
  when: is_master == 1

- import_tasks: deploy_service.yaml

- import_tasks: config_galactica.yaml
  tags: ['conf', 'install', 'conf-galactica', 'install-galactica']

- import_tasks: config_custom.yaml
  tags: ['never', 'conf-custom']

- import_tasks: config_visualdoop.yaml
  tags: ['conf', 'install', 'conf-visualdoop', 'install-visualdoop']
  when: is_master == 1

- import_tasks: drivers.yaml
  tags: [ 'never', 'driver', 'update', 'update-galactica', 'install', 'install-galactica', 'reinstall' ]

- import_tasks: hadoop.yaml
  become: yes
  become_user: root
  tags: [ 'never', 'hadoop' ]

- import_tasks: license.yaml
  tags: [ 'never', 'license' ]

- import_tasks: owner.yaml
  tags: [ 'never', 'owner' ]

- import_tasks: stop_indexima.yaml
  tags: [ 'never', 'restart', 'stop' ]

- import_tasks: start_indexima.yaml
  tags: [ 'never', 'restart', 'start' ]

- import_tasks: manage_service.yaml

- import_tasks: jdbc_url.yaml
  tags: [ 'always', 'jdbc']