---
# Core
- name: manage_service.yaml / Stop Galactica service
  become: yes
  become_user: root
  service:
    name: indexima
    daemon_reload: yes
    state: stopped
  tags: [ 'never', 'grestart', 'gstop', 'istop', 'stop']

# Console
- name: manage_service.yaml / Stop Visualdoop service
  become: yes
  become_user: root
  service:
    name: visualdoop
    daemon_reload: yes
    state: stopped
  tags: [ 'never', 'vrestart', 'vstop', 'istop', 'stop']
  when:
    - is_master == 1

# Core
- name: manage_service.yaml / Enable Galactica service
  become: yes
  become_user: root
  service:
    name: indexima
    daemon_reload: yes
    enabled: yes
  tags: [ 'grestart', 'gstart', 'istart', 'start']

- name: manage_service.yaml / Start Galactica service
  become: yes
  become_user: root
  service:
    name: indexima
    daemon_reload: yes
    state: started
  tags: [ 'grestart', 'gstart', 'istart', 'start']

# Console
- name: manage_service.yaml / Enable Visualdoop service
  become: yes
  become_user: root
  service:
    name: visualdoop
    daemon_reload: yes
    enabled: yes
  tags: [ 'vrestart', 'vstart', 'istart', 'start']
  when:
    - is_master == 1

- name: manage_service.yaml / Start Visualdoop service
  become: yes
  become_user: root
  service:
    name: visualdoop
    daemon_reload: yes
    state: started
  tags: [ 'vrestart', 'vstart', 'istart', 'start']
  when:
    - is_master == 1
