---
- name: Stop Galactica service on workers
  become: yes
  become_user: root
  service:
    name: indeximas
    daemon_reload: yes
    state: stopped
  tags: [ 'never', 'grestart', 'gstop', 'istop', 'stop']
  when:
    - is_master == 0
    - ha == 0

- name: Stop Galactica service on master
  become: yes
  become_user: root
  service:
    name: indeximam
    daemon_reload: yes
    state: stopped
  tags: [ 'never', 'grestart', 'gstop', 'istop', 'stop']
  when:
    - is_master == 1
    - ha == 0

# HA
- name: Stop Galactica service on ha cluster
  become: yes
  become_user: root
  service:
    name: indexima
    daemon_reload: yes
    state: stopped
  tags: [ 'never', 'grestart', 'gstop', 'istop', 'stop']
  when: ha == 1

# VD 2
- name: Stop Visualdoop service
  become: yes
  become_user: root
  service:
    name: visualdoop
    daemon_reload: yes
    state: stopped
  tags: [ 'never', 'vrestart', 'vstop', 'istop', 'stop']
  when:
    - is_master == 1
    - visualdoop|bool

# Dev Console
- name: Stop Devconsole service
  become: yes
  become_user: root
  service:
    name: devconsole
    daemon_reload: yes
    state: stopped
  tags: [ 'never', 'vrestart', 'vstop', 'istop', 'stop']
  when:
    - is_master == 1
    - devconsole|bool

# Standard
- name: Enable Galactica service on workers
  become: yes
  become_user: root
  service:
    name: indeximas
    daemon_reload: yes
    enabled: yes
  tags: [ 'grestart', 'gstart', 'istart', 'start']
  when:
    - is_master == 0
    - ha == 0

- name: Start Galactica service on workers
  become: yes
  become_user: root
  service:
    name: indeximas
    daemon_reload: yes
    state: started
  tags: [ 'grestart', 'gstart', 'istart', 'start']
  when:
    - is_master == 0
    - ha == 0

- name: Enable Galactica service on master
  become: yes
  become_user: root
  service:
    name: indeximam
    daemon_reload: yes
    enabled: yes
  tags: [ 'grestart', 'gstart', 'istart', 'start']
  when:
    - is_master == 1
    - ha == 0

- name: Start Galactica service on master
  become: yes
  become_user: root
  service:
    name: indeximam
    daemon_reload: yes
    state: started
  tags: [ 'grestart', 'gstart', 'istart', 'start']
  when:
    - is_master == 1
    - ha == 0

# HA
- name: Enable Galactica service on ha cluster
  become: yes
  become_user: root
  service:
    name: indexima
    daemon_reload: yes
    enabled: yes
  tags: [ 'grestart', 'gstart', 'istart', 'start']
  when: ha == 1

- name: Start Galactica service on ha cluster
  become: yes
  become_user: root
  service:
    name: indexima
    daemon_reload: yes
    state: started
  tags: [ 'grestart', 'gstart', 'istart', 'start']
  when: ha == 1

# VD2
- name: Enable Visualdoop service
  become: yes
  become_user: root
  service:
    name: visualdoop
    daemon_reload: yes
    enabled: yes
  tags: [ 'vrestart', 'vstart', 'istart', 'start']
  when:
    - is_master == 1
    - visualdoop|bool

- name: Start Visualdoop service
  become: yes
  become_user: root
  service:
    name: visualdoop
    daemon_reload: yes
    state: started
  tags: [ 'vrestart', 'vstart', 'istart', 'start']
  when:
    - is_master == 1
    - visualdoop|bool

# Dev Console
- name: Enable Devconsole service
  become: yes
  become_user: root
  service:
    name: devconsole
    daemon_reload: yes
    enabled: yes
  tags: [ 'vrestart', 'vstart', 'istart', 'start']
  when:
    - is_master == 1
    - devconsole|bool

- name: Start Devconsole service
  become: yes
  become_user: root
  service:
    name: devconsole
    daemon_reload: yes
    state: started
  tags: [ 'vrestart', 'vstart', 'istart', 'start']
  when:
    - is_master == 1
    - devconsole|bool