---
# tasks file for indexima-prerequisites
- name: Echo Starting Indexima
  debug:
    msg: "Starting Indexima"

- name: Start worker nodes
  shell: "(cd {{ galactica_path }} ; nohup {{ galactica_path }}/start-node.sh </dev/null >/dev/null 2>&1 & )"
  when: 
    - is_master == 0

- name: Waiting 5 seconds for workers to start
  pause:
    seconds: 5

- name: Start master node
  shell: "(cd {{ galactica_path }} ; nohup {{ galactica_path }}/start-node.sh --master </dev/null >/dev/null 2>&1 & )"
  when: 
    - is_master == 1

# Deprecated since 173
- name: Start visualdoop on master node
  shell: "(cd {{ indexima_path }}/visualdoop ; nohup {{ indexima_path }}/visualdoop/start-visualdoop.sh </dev/null >/dev/null 2>&1 & )"
  when:
    - is_master == 1
    - indexima_release | replace('.', '') |int < 173
  tags: ['visualdoop']

# Only used if version >= 1.7.3
- name: Start Dev Console on master node
  shell: "(cd {{ vd2_path }} ; nohup {{ vd2_path }}/start.sh </dev/null >/dev/null 2>&1 & )"
  when:
    - is_master == 1
    - indexima_release | replace('.', '') |int >= 173
  tags: ['visualdoop']
