---
- name: start_indexima.yaml / Echo Starting Indexima
  debug:
    msg: "Starting Indexima"

- name: start_indexima.yaml / Start worker nodes
  shell: "(cd {{ galactica_path }} ; nohup {{ galactica_path }}/start-node.sh </dev/null >/dev/null 2>&1 & )"
  when:
    - is_master == 0
    - ha == 0

- name: start_indexima.yaml / Waiting 5 seconds for workers to start
  pause:
    seconds: 5

- name: start_indexima.yaml / Start master node
  shell: "(cd {{ galactica_path }} ; nohup {{ galactica_path }}/start-node.sh --master </dev/null >/dev/null 2>&1 & )"
  when:
    - is_master == 1
    - ha == 0

- name: start_indexima.yaml / Start VD2 on master node
  shell: "(cd {{ vd2_path }} ; nohup {{ vd2_path }}/start.sh </dev/null >/dev/null 2>&1 & )"
  when:
    - is_master == 1

# HA = 1
- name: start_indexima.yaml / Start nodes
  shell: "(cd {{ galactica_path }} ; nohup {{ galactica_path }}/start-node.sh --host {{ service_local_ip }}:{{ node_port }} --attach {{ service_master_ip }}:{{ node_port }} </dev/null >/dev/null 2>&1 & )"
  when:
    - ha == 1

- name: start_indexima.yaml / Waiting 5 seconds for workers to start
  pause:
    seconds: 5
