---
# tasks file for indexima-prerequisites
- name: Echo Stoping Indexima
  debug:
    msg: "Stoping Indexima"

- name: Stop master node
  shell: "(cd {{ indexima_path }}/galactica ; ./stop.sh)"
  when: is_master == 1

- name: Stop VD2 on master node
  shell: "(cd {{ vd2_path }} ; ./stop.sh)"
  when:
    - not devconsole|bool
    - is_master == 1

- name: Stop Dev Console on master node
  shell: "(cd {{ dc_path }} ; ./stop.sh)"
  when:
    - devconsole|bool
    - is_master == 1

- name: Waiting 5 seconds
  pause:
    seconds: 5
