---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    hive_port: 10000
  tasks:
    - name: Wait for Hive server
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ hive_port }}"
        timeout: 300
      when: is_master == 1

    - name: Wait for Monitor server
      wait_for:
        host: "{{ ansible_host }}"
        port: 9999
        timeout: 300
      when: is_master == 1

    - name: Wait for Dev console
      wait_for:
        host: "{{ ansible_host }}"
        port: 8082
        timeout: 300
      when: is_master == 1

    - name: Check if all nodes are up
      uri:
        url: "http://{{ ansible_host }}:9999/api/status"
        follow_redirects: none
        method: GET
      register: _result
      until:
        - _result.status == 200
      retries: 12
      delay: 10
      failed_when: "'serving' not in _result.content"

    - name: Cat galactica.conf
      shell: cat /opt/indexima/galactica/conf/galactica.conf
      register: _galactica_conf

    - name: Cat hive_site.xml
      shell: cat /opt/indexima/galactica/conf/hive-site.xml
      register: _hive_site

    - name : Check if ldap config is correct
      assert:
        that:
          - "'<value>groupOfUniqueNames</value>' in _hive_site.stdout"
          - "'<value>uniqueMember</value>' in _hive_site.stdout"
          - "'<value>cn=%s,ou=crews,ou=groups,dc=indexima,dc=org</value>' in _hive_site.stdout"
          - "'<value>cn=%s,ou=people,dc=indexima,dc=org</value>' in _hive_site.stdout"
          - "'<value>supermen</value>' in _hive_site.stdout"
        fail_msg: "LDAP config went wrong"