---
- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Cleanup galactica_extended
      file:
        path: /tmp/galactica_extended
        state: absent