---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    groups:
      - indexima
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      indexima:
        version: 1.7.11.1183.4
        nodes: 1
        cores: 1
        ram: 600
        partitions: 8
        admin_users: "test_admin"
        service_group: "root"
        warehouse: "/opt/indexima/warehouse"
        indexima_log_path: "/var/log/indexima"
        indexima_hive_log_dir: "/tmp/indexima/hive"
        indexima_history_dir: "/opt/indexima/oldhistory"
        indexima_history_export: "/opt/indexima/newhistory"
        ha: 0
        systemd: false
        cluster_name: docker_test
        galactica_gc_options: "-XX:+UseConcMarkSweepGC -XX:-OmitStackTraceInFastThrow -XX:NewRatio=3"
        galactica_jmx_options: '-verbose:gc'
        drivers: 1
    host_vars:
      instance:
        is_master: 1
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence # commented because of script start
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
