---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Create drivers directory
      file:
        path: /etc/ansible/roles/ansible-indexima-install/files/drivers
        state: directory

    - name: Write custom driver
      copy:
        content: 'mydriver'
        dest: /etc/ansible/roles/ansible-indexima-install/files/drivers/mydriver.jar
    
    - name: Ensure service_group exists
      ansible.builtin.group:
        name: "{{ service_group }}"
        state: present