---
# Verify that Hive, Monitor and Dev Console are reachable. Check that the number of up node is the requested one

- name: Verify
  hosts: all
  vars:
    hive_port: 10000
  tasks:
    - name: Wait for Hive server
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ hive_port }}"
        timeout: 300
      when: is_master == 1

    - name: Wait for Monitor server
      wait_for:
        host: "{{ ansible_host }}"
        port: 9999
        timeout: 300
      when: is_master == 1

    - name: Wait for Dev console
      wait_for:
        host: "{{ ansible_host }}"
        port: 8082
        timeout: 300
      when: is_master == 1

    - name: Check if all nodes are up
      uri:
        url: "http://{{ ansible_host }}:9999/api/get/nodes"
        follow_redirects: none
        method: GET
      register: _result
      until:
        - _result.status == 200
        - _result.json.nodesDown |length == 0
        - _result.json.nodesUp | length == nodes
      retries: 12 # 12 * 5 seconds = 1min
      delay: 5 # Every 5 seconds

    - name: Cat galactica.conf
      shell: cat /opt/indexima/galactica/conf/galactica.conf
      register: _galactica_conf

    - name: Check that partitions = 8
      assert:
        that:
          - partitions == 8
          - "'partitions = 8' in _galactica_conf.stdout"

    - name: Check that cores = 1
      assert:
        that:
          - cores == 1
          - "'cores = 1' in _galactica_conf.stdout"

    - name: Check that log.dir is /var/log/indexima/logs
      assert:
        that:
          - "'log.dir = /var/log/indexima/logs' in _galactica_conf.stdout"

    - name: Check that hive.log.dir is /tmp/indexima/hive
      assert:
        that:
          - "'hive.log.dir = /tmp/indexima/hive' in _galactica_conf.stdout"

    - name: Check that history.dir is /opt/indexima/oldhistory
      assert:
        that:
          - "'history.dir = /opt/indexima/oldhistory' in _galactica_conf.stdout"

    - name: Check that history.export
      assert:
        that:
          - "'history.export = /opt/indexima/newhistory' in _galactica_conf.stdout"

    - name: Check that cluster.name = docker_test
      assert:
        that:
          - "'cluster.name = docker_test' in _galactica_conf.stdout"

    - name: Cat galactica-env.sh
      shell: cat /opt/indexima/galactica/conf/galactica-env.sh
      register: _galactica_env

    - name: Check that galactica mem = 600m
      assert:
        that:
          - ram == 600
          - "'GALACTICA_MEM=420m' in _galactica_env.stdout"

    - name: Check that GC_OPTIONS are customized
      assert:
        that:
          - '"-XX:NewRatio=3" in _galactica_env.stdout'

    - name: Check that JMX_OPTIONS are present and customized
      assert:
        that:
          - >
            "export JMX_OPTIONS='-verbose:gc'" in _galactica_env.stdout

    - name: Stat mydriver.jar
      stat:
        path: /etc/ansible/roles/ansible-indexima-install/files/drivers/mydriver.jar
      register: _mydriver

    - name: Check that mydriver.jar exists
      assert:
        that:
          - _mydriver.stat.exists |bool

    - name: Check that jstack is installed
      command: "jstack -h"

    - name: Check that jmap is installed
      command: "jmap -h"
    
    - name: Cat visualdoop2/config.sh
      shell: cat /opt/indexima/visualdoop2/config.sh
      register: _vd2_config
    
    - name: Check that vd_config.sh has admin as admin_user
      assert:
        that:
          - "'VISUALDOOP_ADMIN=' in _vd2_config.stdout"
        fail_msg: "VISUALDOOP_ADMIN not defined"