---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Delete warehouse if created
      amazon.aws.aws_s3:
        bucket: "{{ warehouse_bucket }}"
        object: "{{ warehouse_key }}"
        mode: delobj
      delegate_to: localhost