---
- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: List all objects in warehouse
      amazon.aws.aws_s3:
        bucket: "{{ indexima_bucket_name }}"
        prefix: "{{ indexima_bucket_prefix }}/warehouse"
        mode: list
      register: _s3_list
      delegate_to: localhost

    - name: Delete warehouse if created
      amazon.aws.aws_s3:
        bucket: "{{ indexima_bucket_name }}"
        object: "{{ item }}"
        mode: delobj
      delegate_to: localhost
      with_items: "{{ _s3_list.s3_keys }}"