---
- name: Converge
  hosts: all
  become: yes
  become_user: "{{ service_user }}"
  tasks:
    - name: "Include ansible-indexima-install"
      include_role:
        name: "ansible-indexima-install"
