---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: instance1
    groups:
      - ec2
    image_owner: ${MOL_AMI_OWNER}
    image_name: ${MOL_AMI_NAME}
    instance_type: t2.micro
    vpc_subnet_id: subnet-a53d65cc
    instance_tags:
      - Name: molecule_instance1_${MOL_ENV_NAME}
  - name: instance2
    groups:
      - ec2
    image_owner: ${MOL_AMI_OWNER}
    image_name: ${MOL_AMI_NAME}
    instance_type: t2.micro
    vpc_subnet_id: subnet-a53d65cc
    instance_tags:
      - Name: molecule_instance2_${MOL_ENV_NAME}
provisioner:
  name: ansible
  log: True
  inventory:
    group_vars:
      ec2:
        nodes: 2
        warehouse_type: s3
        indexima_bucket_name: ${AWS_TEST_BUCKET_NAME}
        indexima_bucket_prefix: molecule/s3test
    host_vars:
      localhost:
        remote_user: ${MOL_SSH_USER}
        molecule_env_name: ${MOL_ENV_NAME}
        indexima_bucket_name: ${AWS_TEST_BUCKET_NAME}
        indexima_bucket_prefix: molecule/s3test
      instance1:
        is_master: 1
      instance2:
        is_master: 0
verifier:
  name: ansible
