---
  # Verify that Hive, Monitor and Dev Console are reachable. Check that the number of up node is the requested one

- name: Verify
  hosts: all
  vars:
    hive_port: 10000
  tasks:
    - name: Wait for Hive server
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ hive_port }}"
        timeout: 300
      when: is_master == 1

    - name: Wait for Monitor server
      wait_for:
        host: "{{ ansible_host }}"
        port: 9999
        timeout: 300
      when: is_master == 1

    - name: Wait for Dev console
      wait_for:
        host: "{{ ansible_host }}"
        port: 8082
        timeout: 300
      when: is_master == 1

    - name: Check if all nodes are up
      uri:
        url: "http://{{ ansible_host }}:9999/api/get/nodes"
        follow_redirects: none
        method: GET
      register: _result
      until:
        - _result.status == 200
        - _result.json.nodesDown |length == 0
        - _result.json.nodesUp | length == nodes
      retries: 12 # 12 * 5 seconds = 1min
      delay: 5 # Every 5 seconds

    - name: Check if warehouse is created
      amazon.aws.aws_s3:
        bucket: "{{ indexima_bucket_name }}"
        prefix: "{{ indexima_bucket_prefix }}/warehouse"
        mode: list
      register: _s3_list
      delegate_to: localhost
      failed_when: _s3_list.s3_keys | length != 1
